// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/davidbz/lantern/internal/mdns"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBrowser creates a new instance of MockBrowser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBrowser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBrowser {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockBrowser{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockBrowser is an autogenerated mock type for the Browser type
type MockBrowser struct {
	mock.Mock
}

type MockBrowser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBrowser) EXPECT() *MockBrowser_Expecter {
	return &MockBrowser_Expecter{mock: &_m.Mock}
}

// Browse provides a mock function for the type MockBrowser
func (_mock *MockBrowser) Browse(ctx context.Context, service string) ([]mdns.Record, error) {
	ret := _mock.Called(ctx, service)

	if len(ret) == 0 {
		panic("no return value specified for Browse")
	}

	var r0 []mdns.Record
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]mdns.Record, error)); ok {
		return returnFunc(ctx, service)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []mdns.Record); ok {
		r0 = returnFunc(ctx, service)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]mdns.Record)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, service)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBrowser_Browse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Browse'
type MockBrowser_Browse_Call struct {
	*mock.Call
}

// Browse is a helper method to define mock.On call
//   - ctx context.Context
//   - service string
func (_e *MockBrowser_Expecter) Browse(ctx any, service any) *MockBrowser_Browse_Call {
	return &MockBrowser_Browse_Call{Call: _e.mock.On("Browse", ctx, service)}
}

func (_c *MockBrowser_Browse_Call) Run(run func(ctx context.Context, service string)) *MockBrowser_Browse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBrowser_Browse_Call) Return(records []mdns.Record, err error) *MockBrowser_Browse_Call {
	_c.Call.Return(records, err)
	return _c
}

func (_c *MockBrowser_Browse_Call) RunAndReturn(run func(ctx context.Context, service string) ([]mdns.Record, error)) *MockBrowser_Browse_Call {
	_c.Call.Return(run)
	return _c
}
