// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"net/netip"

	"github.com/mdlayher/arp"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConn creates a new instance of MockConn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConn(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConn {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockConn{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockConn is an autogenerated mock type for the Conn type
type MockConn struct {
	mock.Mock
}

type MockConn_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConn) EXPECT() *MockConn_Expecter {
	return &MockConn_Expecter{mock: &_m.Mock}
}

// Read provides a mock function for the type MockConn
func (_mock *MockConn) Read(ctx context.Context) (*arp.Packet, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 *arp.Packet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*arp.Packet, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *arp.Packet); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*arp.Packet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConn_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockConn_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockConn_Expecter) Read(ctx any) *MockConn_Read_Call {
	return &MockConn_Read_Call{Call: _e.mock.On("Read", ctx)}
}

func (_c *MockConn_Read_Call) Run(run func(ctx context.Context)) *MockConn_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConn_Read_Call) Return(packet *arp.Packet, err error) *MockConn_Read_Call {
	_c.Call.Return(packet, err)
	return _c
}

func (_c *MockConn_Read_Call) RunAndReturn(run func(ctx context.Context) (*arp.Packet, error)) *MockConn_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Request provides a mock function for the type MockConn
func (_mock *MockConn) Request(ctx context.Context, ip netip.Addr) error {
	ret := _mock.Called(ctx, ip)

	if len(ret) == 0 {
		panic("no return value specified for Request")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, netip.Addr) error); ok {
		r0 = returnFunc(ctx, ip)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConn_Request_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Request'
type MockConn_Request_Call struct {
	*mock.Call
}

// Request is a helper method to define mock.On call
//   - ctx context.Context
//   - ip netip.Addr
func (_e *MockConn_Expecter) Request(ctx any, ip any) *MockConn_Request_Call {
	return &MockConn_Request_Call{Call: _e.mock.On("Request", ctx, ip)}
}

func (_c *MockConn_Request_Call) Run(run func(ctx context.Context, ip netip.Addr)) *MockConn_Request_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 netip.Addr
		if args[1] != nil {
			arg1 = args[1].(netip.Addr)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConn_Request_Call) Return(err error) *MockConn_Request_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConn_Request_Call) RunAndReturn(run func(ctx context.Context, ip netip.Addr) error) *MockConn_Request_Call {
	_c.Call.Return(run)
	return _c
}
