// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/davidbz/lantern/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockInterfaceLister creates a new instance of MockInterfaceLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInterfaceLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInterfaceLister {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockInterfaceLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockInterfaceLister is an autogenerated mock type for the InterfaceLister type
type MockInterfaceLister struct {
	mock.Mock
}

type MockInterfaceLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInterfaceLister) EXPECT() *MockInterfaceLister_Expecter {
	return &MockInterfaceLister_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type MockInterfaceLister
func (_mock *MockInterfaceLister) List(ctx context.Context) ([]domain.Interface, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Interface
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.Interface, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.Interface); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Interface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInterfaceLister_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockInterfaceLister_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockInterfaceLister_Expecter) List(ctx any) *MockInterfaceLister_List_Call {
	return &MockInterfaceLister_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockInterfaceLister_List_Call) Run(run func(ctx context.Context)) *MockInterfaceLister_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInterfaceLister_List_Call) Return(interfaces []domain.Interface, err error) *MockInterfaceLister_List_Call {
	_c.Call.Return(interfaces, err)
	return _c
}

func (_c *MockInterfaceLister_List_Call) RunAndReturn(run func(ctx context.Context) ([]domain.Interface, error)) *MockInterfaceLister_List_Call {
	_c.Call.Return(run)
	return _c
}
