// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/davidbz/lantern/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockScanner creates a new instance of MockScanner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScanner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScanner {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockScanner{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockScanner is an autogenerated mock type for the Scanner type
type MockScanner struct {
	mock.Mock
}

type MockScanner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScanner) EXPECT() *MockScanner_Expecter {
	return &MockScanner_Expecter{mock: &_m.Mock}
}

// Scan provides a mock function for the type MockScanner
func (_mock *MockScanner) Scan(ctx context.Context, prev domain.Inventory) (domain.ScanResult, error) {
	ret := _mock.Called(ctx, prev)

	if len(ret) == 0 {
		panic("no return value specified for Scan")
	}

	var r0 domain.ScanResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Inventory) (domain.ScanResult, error)); ok {
		return returnFunc(ctx, prev)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Inventory) domain.ScanResult); ok {
		r0 = returnFunc(ctx, prev)
	} else {
		r0 = ret.Get(0).(domain.ScanResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Inventory) error); ok {
		r1 = returnFunc(ctx, prev)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockScanner_Scan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scan'
type MockScanner_Scan_Call struct {
	*mock.Call
}

// Scan is a helper method to define mock.On call
//   - ctx context.Context
//   - prev domain.Inventory
func (_e *MockScanner_Expecter) Scan(ctx any, prev any) *MockScanner_Scan_Call {
	return &MockScanner_Scan_Call{Call: _e.mock.On("Scan", ctx, prev)}
}

func (_c *MockScanner_Scan_Call) Run(run func(ctx context.Context, prev domain.Inventory)) *MockScanner_Scan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Inventory
		if args[1] != nil {
			arg1 = args[1].(domain.Inventory)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockScanner_Scan_Call) Return(scanResult domain.ScanResult, err error) *MockScanner_Scan_Call {
	_c.Call.Return(scanResult, err)
	return _c
}

func (_c *MockScanner_Scan_Call) RunAndReturn(run func(ctx context.Context, prev domain.Inventory) (domain.ScanResult, error)) *MockScanner_Scan_Call {
	_c.Call.Return(run)
	return _c
}
