// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/davidbz/lantern/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSource creates a new instance of MockSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSource {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockSource is an autogenerated mock type for the Source type
type MockSource struct {
	mock.Mock
}

type MockSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSource) EXPECT() *MockSource_Expecter {
	return &MockSource_Expecter{mock: &_m.Mock}
}

// Discover provides a mock function for the type MockSource
func (_mock *MockSource) Discover(ctx context.Context, ifaces []domain.Interface) ([]domain.Observation, error) {
	ret := _mock.Called(ctx, ifaces)

	if len(ret) == 0 {
		panic("no return value specified for Discover")
	}

	var r0 []domain.Observation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.Interface) ([]domain.Observation, error)); ok {
		return returnFunc(ctx, ifaces)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.Interface) []domain.Observation); ok {
		r0 = returnFunc(ctx, ifaces)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Observation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []domain.Interface) error); ok {
		r1 = returnFunc(ctx, ifaces)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSource_Discover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Discover'
type MockSource_Discover_Call struct {
	*mock.Call
}

// Discover is a helper method to define mock.On call
//   - ctx context.Context
//   - ifaces []domain.Interface
func (_e *MockSource_Expecter) Discover(ctx any, ifaces any) *MockSource_Discover_Call {
	return &MockSource_Discover_Call{Call: _e.mock.On("Discover", ctx, ifaces)}
}

func (_c *MockSource_Discover_Call) Run(run func(ctx context.Context, ifaces []domain.Interface)) *MockSource_Discover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []domain.Interface
		if args[1] != nil {
			arg1 = args[1].([]domain.Interface)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSource_Discover_Call) Return(observations []domain.Observation, err error) *MockSource_Discover_Call {
	_c.Call.Return(observations, err)
	return _c
}

func (_c *MockSource_Discover_Call) RunAndReturn(run func(ctx context.Context, ifaces []domain.Interface) ([]domain.Observation, error)) *MockSource_Discover_Call {
	_c.Call.Return(run)
	return _c
}
