// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockVendorUpdater creates a new instance of MockVendorUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVendorUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVendorUpdater {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockVendorUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockVendorUpdater is an autogenerated mock type for the VendorUpdater type
type MockVendorUpdater struct {
	mock.Mock
}

type MockVendorUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVendorUpdater) EXPECT() *MockVendorUpdater_Expecter {
	return &MockVendorUpdater_Expecter{mock: &_m.Mock}
}

// Update provides a mock function for the type MockVendorUpdater
func (_mock *MockVendorUpdater) Update(ctx context.Context) (int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVendorUpdater_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockVendorUpdater_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockVendorUpdater_Expecter) Update(ctx any) *MockVendorUpdater_Update_Call {
	return &MockVendorUpdater_Update_Call{Call: _e.mock.On("Update", ctx)}
}

func (_c *MockVendorUpdater_Update_Call) Run(run func(ctx context.Context)) *MockVendorUpdater_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVendorUpdater_Update_Call) Return(n int, err error) *MockVendorUpdater_Update_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockVendorUpdater_Update_Call) RunAndReturn(run func(ctx context.Context) (int, error)) *MockVendorUpdater_Update_Call {
	_c.Call.Return(run)
	return _c
}
